language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: liBL2xfFLzBY/NOKVHletdePG0t/KpLllfUdReCeln5uNw7qHtVhCg6dJitI6JPDBXw8vOw9LOBYklikaNzNFtnyt46Uk7m/PkNkvTFM0IlYpeY/WymGcT8Det3R68XcqDYLj+sQS0wqzHIHFEE8cbN9s2zu/Vby6cymuMguAPbSHPEuV4qLWhEAsrKuwYQv+7oD2HRzcspGyHzHyQnMSzYPGqM1dXenMKvcvrvgLRbxZ/gM4q98JOzV5fNVHieoTKEa34OdA34h7il509ZYSmjCaausV3U11JFa7QBr/X4mvGDcQsvT4Tz4Om2U8wWfdwRyc+JZ26ANmYg46kcnkLhLPDZcRAOIeS+CqAG/Sg7qGcCSloQv9xIr+Fx7hv3j84Y+N/dT0XHH7qoj7vrViDo9lK7tG5ttPq12ooxje04aUgoCFkXr37u/QeKx2uFrLX6ZT+oialJVgleSSa7p9Be4Lmqg8VLIvO2anNzWH6f00MbT+e+NFLn9Y07zrcbzoq6opSHOoNtmx3LLLEyrJqQr13X5UhXhuvsQpYDwvVQClRzSEIkSpd392sMNh8+PzpWgtxbvuHpkQuoLoLr7A4V1pMdOUXwdreC4nqf39hY8vVbxBUiynTNSp8Mu5lOjFGleuxgiqIm4TVagwL45Twq19YkeIcE6IT0Rw/MmxzE=
  app: quikeatz
  on:
    repo: PeterBen90/node-quikeatz-app
